### ISSUE TITLE
1.2.0 Exception in server tick loop

### ISSUE THREAD

**Issue by zepanv** [FTBTeam/FTB-Interactions#281] opened 2019-04-11 22:23 UTC
## Modpack Version: 
1.2.0

## Bug Report:
Exception in server tick loop

## Expected Behavior/Suggestions:
Not to have Exception in server tick loop

## Is It Repeatable? Steps to Reproduce: 

1. Load world
2. Crash

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/0ee538e4

**Comment by Vyraal1** [comment] 2019-04-11 22:25
Do you mind providing more information to: https://github.com/HellFirePvP/AstralSorcery/issues/1068

**Comment by ClockwiseGear** [comment] 2019-04-11 22:35
+1 report:
https://pastebin.com/55229vZ7
Also notified the indicated issue above

**Comment by Shadowgar** [comment] 2019-04-12 04:35
Duplicate of #282 This was solved.

**Comment by The-Snakes** [comment] 2019-04-12 05:06
You can replace the file from the below path with the one attached after removing the .txt extension.
Local:
C:\Users\%username%\Documents\Curse\Minecraft\Instances\FTB Interactions\config\astralsorcery\
Server:
FTBInteractionsServer_1.2.0\config\astralsorcery\

[fluid_rarities.cfg.txt](https://github.com/FTBTeam/FTB-Interactions/files/3071628/fluid_rarities.cfg.txt)

**Comment by zepanv** [comment] 2019-04-12 08:23
I wouldn't say it's solved until the pack updates with a fixed file, I didn't modify the file to begin with.

**Comment by Saereth** [comment] 2019-04-12 13:16
Please see The-Snake's fix, I put the updated fluid rarities file on our google drive for everyone, his instructions are correct. This is in the new hotfix for the pack 1.2.1 which will be out asap.

**Closed** 2019-04-17 17:55 UTC
Labels: fixed in next update, mod issue
