### ISSUE TITLE
Satchel^3 doesn't recognize crafted Holding IV satchel

### ISSUE THREAD

**Issue by TomyLobo** [FTBTeam/FTB-Interactions#406] opened 2019-04-20 22:55 UTC
## Modpack Version: 
1.3.0

## Bug Report:
You might have overcorrected a bit on #271 :)
Now it's not recognizing a crafted holding IV Satchel.
I crafted 5 basic satchels from black wool, tin and leather, combined them and the quest isn't recognizing it.

**Comment by KaneHart** [comment] 2019-04-26 14:30
Still an issue in 1.4.1 https://i.imgur.com/itVjWIp.png

**Comment by Vyraal1** [comment] 2019-04-26 16:59
Duplicate of https://github.com/FTBTeam/FTB-Interactions/issues/370

Unfortunately due to GTCE's breaking update, I'm not sure of a workaround or this other than  starting a world in 1.1.0 and then updating the pack to 1.2+. All worlds created using GTCE 387 will have this problem. Might need an entirely different workaround or just removing this recipe altogether.

**Closed by Vyraal1** 2019-04-26 16:59 UTC

**Comment by TomyLobo** [comment] 2019-04-27 09:12
the world was started in 1.0.1 i think

**Comment by ray73864** [comment] 2019-05-06 22:43
Having this issue with my SSP game, I crafted 5 basic satchels, combined them together, the resultant satchel has Holding IV on it, but the task refuses to complete, even clicking on 'Quick Complete' fails.

I am running 1.5.0 of FTB:I, I created the world originally with version 1.3.0.

http://puu.sh/DoMgS/8f458d132b.jpg
http://puu.sh/DoMhm/56d6c24280.jpg

**Comment by Vyraal1** [comment] 2019-05-06 23:09
Due to the difficulty of solving this we might just remove the recipe entirely for 1.6.0. As a result the quest will also be removed as well. This issue still persists with anything that also lets the player craft Holding IV books, and etc.

**Comment by TomyLobo** [comment] 2019-05-07 06:18
eh, why throw the baby out with the bathwater?
just make the quest require you to get 5 satchels and have the description state how to combine them.

**Comment by KaneHart** [comment] 2019-05-07 07:50
That is not even the issue Tomy. It's the enchant id's kept switching up and so when you combined 5 you don't even get the intended purpose. The idea is to remove it since it's useless now. Nothing more.

**Comment by TomyLobo** [comment] 2019-05-07 16:41
I crafted mine and it still has the same properties, so I can't quite see the issue here.

**Comment by KaneHart** [comment] 2019-05-07 17:36
How old is your save? From my understanding it's newer saves that cause it. I think the enchant data stored in the level.dat so that way it does not shuffle around and break stuff in the current game.

**Comment by ray73864** [comment] 2019-05-07 21:09
Mine has the correct enchantment on it (Holding IV), I crafted 2 of them (Had to, accidentally used the first one to create the void satchel...), both had Holding IV on them, but neither triggered the quest to be completed.

**Comment by TomyLobo** [comment] 2019-05-08 06:12
my save is from 1.0.1 if i remember correctly
