### ISSUE TITLE
Wiring Inconsistencies in GTCE

### ISSUE THREAD

**Issue by Vyraal1** [FTBTeam/FTB-Interactions#531] opened 2019-04-30 18:35 UTC
1) Verify this is reproducible in GTCE 391

**Comment by Vyraal1** [comment] 2019-04-30 18:36
https://gfycat.com/redquarrelsomeaustrianpinscher

**Comment by hobnob11** [comment] 2019-04-30 18:40
See gif, because of how overclocking works currently, and because machines have an amperage limit of 1 amp. 

Both machines in the example "should" die because while they both have access to 2 amps of lv, more than enough for the 32 eu a tick they want, they can only draw one amp of that, meaning that after cable loss they get less than 32 eu/tick and die.

However, (and this is an assumption i dont fully understand the java yet) because from what i've tested the logic for sending out energy is done on the power source, not the cable "multiblock", the logic happens more than once per tick. causing the back machine which has 2 power sources to actually accept 2 amps /tick.

The front machine, which as you can see has the same power source, has the power going through 2 transformers, converting the "two sources" of 1 amp into "one source" of 4 amps (while the buffer is full anyway), as it can only draw 1 amp from this, it only gets about 30 eu/tick and dies.

**Comment by hobnob11** [comment] 2019-04-30 19:14
update has changed *everything* testing has unveiled new laws of physics.
![gif](https://im.ezgif.com/tmp/ezgif-1-34798961ab5a.gif)

**Comment by hobnob11** [comment] 2019-04-30 19:37
I dont reccomend moving to the new version until batteries are fixed, as this can very quickly lead to crashing. https://gfycat.com/timelyflatafghanhound

I'd continue testing the new wiring logic, but I cant load my test world anymore so I'll wait..

**Comment by Vyraal1** [comment] 2019-04-30 20:01
I'm not particularly worried about it crashing if players are using infinite batteries, can you replicate this crash under actual testing conditions? 

Also your other gif isn't loading, need more information, no idea what you're going on about.

**Comment by hobnob11** [comment] 2019-04-30 20:15
Okay so the first .gif is showing how *all* batteries currently ignore max limits, they will just keep charging beyond any limits. the second gif shows how using the tier 8 batteries causes this "no max limit" bug to crash the game, but this would happen eventually with lower tier batteries.

**Comment by hobnob11** [comment] 2019-04-30 20:22
![gif](https://i.imgur.com/JmJiQWE.gif) the actual issue is any battery can charge beyond its max, i used batteries that start at max long to show how when they charge past max long it would crash, but any battery would eventually get to this.

**Comment by Vyraal1** [comment] 2019-04-30 20:30
https://streamable.com/9mmdo

Ok Hob really appreciate this but I need to get steps on how to reproduce this, I'm not getting the same results.

**Comment by hobnob11** [comment] 2019-04-30 20:50
Okay so, the crash is caused by the amount of eu stored in the battery going over long.MAX_VALUE (the biggest number you can store in a long type number, which is what gtce uses for energy) (actually i think it might be something like the one probe trying to display it causing the crash but anyway) 

In my example i use the teir 8 batteries as they start out at max long, so waiting for them to charge past max long to cause crashes didnt take very long. but I would expect the same crash for any tier of battery once they had charged past max long. 

I just tested your example, and it appears the bug is limited to battery buffers, battery chargers do not appear to have the same issue. 

![gif](https://thumbs.gfycat.com/IndelibleNarrowErmine-size_restricted.gif)
([alt link to gif](https://gfycat.com/indeliblenarrowermine))

**Comment by hobnob11** [comment] 2019-04-30 20:53
As pointed out by kanzuke, the probable cause of this is the new feature added to battery buffers (but not chargers) in the latest update; Parallel charging.

**Comment by hobnob11** [comment] 2019-04-30 20:58
see https://github.com/GregTechCE/GregTech/issues/780

**Closed** 2019-06-14 16:44 UTC
Labels: bug, fixed in next update
