### ISSUE TITLE
CTD Xaero's Minimap

### ISSUE THREAD

**Issue by Selway00** [FTBTeam/FTB-Interactions#624] opened 2019-05-17 04:34 UTC
## Modpack Version: 
1.6

## Bug Report:
Multiple CTD while playing on the ToAsgaard Patreon server.  Server was unaffected.  It may be related to this problem https://minecraft.curseforge.com/projects/xaeros-minimap/issues/31

But the suggested fix does not seem to work.  

I will post this on the mod page in the morning.  Something is wrong with my log in there and its too late for me to mess with it now!

Thanks for all your hard work.  Great pack!

## Expected Behavior/Suggestions:
No CTD when the minimap is loading

## Is It Repeatable? Steps to Reproduce: 
It crashes every time for me but I dont know how someone else would go about repeating it.

## Link to Log or Crash File Paste**: 
https://pastebin.com/yVc2ZEdB

## Mod/s Affected: 
Xaero's Minimap

## Known Fix: 
The author claims reloading the pack a couple of times works.  I think I am on my 8th try.

**Comment by Selway00** [comment] 2019-05-17 04:46
I should also point out that my Y position is 286 which another issue pointed out may be causing the crash.

**Comment by KaneHart** [comment] 2019-05-17 07:17
You are crashing because the mini map. Update it manually to the latest version. 

Duplicate of #616

**Comment by Selway00** [comment] 2019-05-17 14:55
Thank you.  This corrected the problem on my end.

**Closed** 2019-05-20 19:32 UTC
Labels: bug, duplicate, fixed in next update
