### ISSUE TITLE
Suggestion: add menril logs to oredict of logWood

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#173] opened 2019-04-03 01:04 UTC
Currently they're only logMenril, this prevents them from being usable in the pyrolase oven; granted this isn't breaking in any way just more of an inconvience feel free to kill the issue if you don't want to.

Submitter: `IRSmoh_#5048`
Body: `OwO issue "Suggestion: add menril logs to oredict of logWood" "Currently they're only logMenril, this prevents them from being usable in the pyrolase oven; granted this isn't breaking in any way just more of an inconvience feel free to kill the issue if you don't want to."`
Attachments:

**Comment by Vyraal1** [comment] 2019-04-03 01:10
Duplicate of https://github.com/FTBTeam/FTB-Interactions/issues/169

**Closed by Vyraal1** 2019-04-03 01:10 UTC
Labels: duplicate
