### ISSUE TITLE
Coagulated Plant Balls don't copy Cohosh

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#361] opened 2019-04-17 21:45 UTC
Submitter: `Saber#3492`
Body: `OwO issue "Coagulated Plant Balls don't copy Cohosh"`
Attachments:

**Comment by Saberawr** [comment] 2019-04-17 21:52
Tested accidentally with a roof, apparently plant balls don't copy anything with a roof over the area

**Comment by Vyraal1** [comment] 2019-04-18 01:11
Dupe of https://github.com/FTBTeam/FTB-Interactions/issues/239

**Closed by Vyraal1** 2019-04-18 01:11 UTC
Labels: duplicate
