### ISSUE TITLE
Memory Leak On Server

### ISSUE THREAD

**Issue by Icysnowman** [FTBTeam/FTB-Interactions#1369] opened 2022-01-02 14:28 UTC
## Modpack Version: 
2.0.9

## Bug Report:
I am running a server of this on my windows PC over time i am getting memory issues where all of the computers ram is being used up by the server and it is slowing the server down to a point where there is HUGE delay like 20 secconds even connecting via local ip. This is also the same for other users playing, the TPS is 20 on the server so not an issue there.
Just after starting the server it is using 4,696MB of memory i have tried changing java launch arguments to  "java.exe -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx10240M -Xms4250M -XX:MaxPermSize=256M -XX:+DisableExplicitGC -jar forge-1.12.2-14.23.5.2859-universal.jar nogui " it slows down how long it takes for the error to occur but after about 12 hours of the server running i am seeing this fault. I have also tried upgrading the forge version to a newer one to see if that would help. I also installed Tick Profiler after getting this fault to see if that shows anything but with my limited knowledge it doesn't show much 

## Expected Behavior/Suggestions:
Bug: After 12 hours memory reaches 10GB used and server is very slow to respond.  Restarting this always fixes it for around 12 hours
Suggestions: Not maxing memory out with nothing changing never seen this error on any server i have ran. 

## Is It Repeatable? Steps to Reproduce: 

1. It occurs every time very repeatable but not sure how to show evidence as it just increases slowly over 12 hours till this fault happens. 

## Link to Log or Crash File Paste**: 
This is the last crash log if i leave it going for extended periods of time, join find out its bugging out try to save but the delay is around the 1 min mark the server crashes and this is the report. 
https://paste.feed-the-beast.com/view/559aad2b

This is what the console spams over and over when i look it it after about 12 hours .
https://paste.feed-the-beast.com/view/30fd30f0

**Comment by Saereth** [comment] 2022-05-11 15:57
believe this was caused by logistics pipes and should be fixed with the new update

**Closed by Saereth** 2022-05-11 15:57 UTC
Labels: fixed in next update
