### ISSUE TITLE
GT Flint Axe is still not working in 1.9.1

### ISSUE THREAD

**Issue by WessonChen** [FTBTeam/FTB-Interactions#728] opened 2019-06-26 20:18 UTC
yep last update broke gt axes, should be fixed in this new update

_Originally posted by @Saereth in https://github.com/FTBTeam/FTB-Interactions/issues/711#issuecomment-505043150_

------------------------------------------------------------

Sorry, but it is still not fixed in 1.9.1.

**Comment by bmpotter13** [comment] 2019-07-06 21:26
Seconding that it's not fixed with 1.9.1 release nor mentioned in changelog that it "was fixed".

**Comment by BitsBytesGaming** [comment] 2019-07-06 22:01
Can confirm.
https://www.youtube.com/watch?v=oZ4myIj5iUg

**Comment by bmpotter13** [comment] 2019-07-06 22:58
Update -- **all GregTech axes** don't work. I've tested with

- Iron
- Aluminum
- Iridium
- Chrome
- Manganese
- Darmstadium
- Flint

There hasn't been a reported issue on the Gregtech git repo about axes not working.

**Comment by danstrother** [comment] 2019-07-06 23:30
This is an issue with the GTCE version that is used by 1.9.1 (1.8.3.418).

There is a closed issue on the GTCE tracker:
https://github.com/GregTechCE/GregTech/issues/862

Updating to the latest GTCE version (1.8.4.419) fixes it (though I've only tested the flint axe, and I've only just left the void world so I can't say whether updating will cause any other regressions).

**Comment by BitsBytesGaming** [comment] 2019-07-07 20:28
Please update the GTCE version to 1.8.4.419 asap, as **community server** admins are unable to do anything unless the pack is updated.

**Comment by NachtRaben** [comment] 2019-09-12 01:47
```
[21:38:00] [Server thread/DEBUG] [BnBGamingCore]: Caught Exception while attempting to get class extensions for net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1826_GregicAdditions_registerRecipes_Register
java.lang.ArrayIndexOutOfBoundsException: 8
        at gregicadditions.recipes.MachineCraftingRecipes.init(MachineCraftingRecipes.java:184) ~[MachineCraftingRecipes.class:?]
        at gregicadditions.GregicAdditions.registerRecipes(GregicAdditions.java:77) ~[GregicAdditions.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1826_GregicAdditions_registerRecipes_Register.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) ~[EventBus$1.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857) [GameData.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:629) [CraftingHelper.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
Simply updating is not an option due to an issue with BnBGamingCore, but there has been no updates to that mod.

**Comment by NazTDragN** [comment] 2019-09-29 21:51
Just installed fresh and started playing FTB Interactions 5-10 min ago and GT Axe STILL not working.
Kinda sad that one of the main pack mechanics doesn't work and hasn't been (to my knowledge) even addressed, since the most recent posts I have found about the problem so far are from back in July 2mo. ago.

**Comment by MilanDierickGD** [comment] 2019-10-05 13:10
Can confirm, still not working!

**Comment by jellonek** [comment] 2019-11-11 09:17
Bumping up.

**Comment by mikkerlo** [comment] 2019-12-21 10:35
Bump

**Comment by KlumsyKyller** [comment] 2020-03-24 06:49
Bump

**Comment by Saereth** [comment] 2020-03-24 14:49
I said it was fixed in the new update, the new update has not been release. This is a duplicate and already address, bumping it wont help the FTB launcher be ready faster, go harass slowpoke or something :p

**Comment by KlumsyKyller** [comment] 2020-03-24 21:26
Ah, sorry, it hadn't been said in this thread, which was the only one I checked. Thanks for the quick response!

**Closed** 2020-05-23 17:46 UTC
Labels: bug, duplicate, fixed in next update

**Comment by donq123** [comment] 2020-08-01 23:31
I am still having this issue

**Comment by Saereth** [comment] 2020-08-03 18:23
then you're version is out of date, make sure you're on the latest from the ftb app
