### ISSUE TITLE
ServerHangWatchdog crash, possibly related to large boiler and/or Mekanism pipes

### ISSUE THREAD

**Issue by felix-schneider** [FTBTeam/FTB-Interactions#400] opened 2019-04-20 15:13 UTC
## Modpack Version: 
1.2.2

## Bug Report:
The server crashes. Most recently, I built a large bronze boiler, 5 advanced coke ovens and established a rather long Mekanism item pipe connection, so it may be related to that.

## Expected Behavior/Suggestions:
N/A

## Is It Repeatable? Steps to Reproduce: 
The server crashes again as soon as I reconnect

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/d373df11

https://paste.feed-the-beast.com/view/e05ea8df

## Mod/s Affected: 
None confirmed

Edit:
The server ran long enough to get a debug profile (`/debug start` and `/debug stop`). Initially, the problem seemed to be the Mekanism pipes. However, after removing all of them, the problem persists.
https://paste.feed-the-beast.com/view/5e396fe2

**Comment by Vyraal1** [comment] 2019-04-20 18:16
Not really sure what might be going on here, any modifications made to the pack?

**Comment by felix-schneider** [comment] 2019-04-20 18:18
No, just the regular pack

**Comment by Vyraal1** [comment] 2019-04-20 18:22
Only other catch all solution I can think of is going into Forge.cfg and there should be a line regarding erroring tile entities being deleted, set that to true and see if that lets you get back into the world. Otherwise not really sure what to read from the crash report.

**Comment by liketechnik** [comment] 2019-04-22 22:04
I'm not sure if this is helpful, but these crashes both seem related to synchronization issues that aren't tied to a specific mod. The first log indicates that a lockup occurred that was possibly caused by jline, which forge uses for the server console.

**Comment by Gunner76th** [comment] 2019-05-01 12:54
To temporarily disable the Watchdog, and thus prevent it from terminating the server you need to edit/add the following setting to your server.properties file: 

max-tick-time | integer (0–(2^63 - 1)) | 60000 | The maximum number of milliseconds a single tick may take before the server watchdog stops the server with the message, A single server tick took 60.00 seconds (should be max 0.05); Considering it to be crashed, server will forcibly shutdown. Once this criterion is met, it calls System.exit(1).-1 - disable watchdog entirely (this disable option was added in 14w32a)
-- | -- | -- | --


This could give you more time to isolate the root cause of the excessive tick time, and ultimately the root cause of the issue.

**Comment by Saereth** [comment] 2019-05-07 17:52
new mek updates should hopefully resolves, either way cant reproduce so closing for now

**Closed by Saereth** 2019-05-07 17:52 UTC
Labels: help wanted
