### ISSUE TITLE
Handy Bag still requires Insight 4 Satchel

### ISSUE THREAD

**Issue by ZeekDaGeek** [FTBTeam/FTB-Interactions#370] opened 2019-04-18 14:25 UTC
## Modpack Version: 
1.3.0

## Bug Report:
Handy Bag still requires Insight 4 Satchel
`./scripts/EnderUtilities.zs` line 157

Edit: `./scripts/ThermalExpansion.zs` line 68 - 81 also say id: 39

**Comment by Vyraal1** [comment] 2019-04-18 14:59
![image](https://user-images.githubusercontent.com/26587049/56370297-f697ae80-61c8-11e9-9ebb-eb69071554d8.png)

When was your world created? This was from a fresh install of the pack.

**Comment by ZeekDaGeek** [comment] 2019-04-18 15:33
I attempted to restart the game and start a new world but even in singleplayer Insight is 39 and holding is 38 for me. Here's the output:

```
+------------------------------------------+---------------------------------------------+---------------+-----------+----+
| Registry name                            | Name                                        | Type          | Rarity    | ID |
+------------------------------------------+---------------------------------------------+---------------+-----------+----+
| advancedrocketry:spacebreathing          | enchantment.spaceBreathing                  | ARMOR         | COMMON    | 27 |
| apotheosis:berserk                       | enchantment.apotheosis.berserk              | ARMOR         | VERY_RARE | 69 |
| apotheosis:capturing                     | enchantment.spw.capturing                   | WEAPON        | VERY_RARE | 77 |
| apotheosis:depth_miner                   | enchantment.apotheosis.depth_miner          | DIGGER        | UNCOMMON  | 59 |
| apotheosis:hell_infusion                 | enchantment.apotheosis.hell_infusion        | WEAPON        | VERY_RARE | 57 |
| apotheosis:icy_thorns                    | enchantment.apotheosis.icy_thorns           | ARMOR_CHEST   | RARE      | 65 |
| apotheosis:knowledge                     | enchantment.apotheosis.knowledge            | WEAPON        | RARE      | 72 |
| apotheosis:life_mending                  | enchantment.apotheosis.life_mending         | BREAKABLE     | VERY_RARE | 64 |
| apotheosis:magic_protection              | enchantment.apotheosis.magic_protection     | ARMOR         | UNCOMMON  | 76 |
| apotheosis:mounted_strike                | enchantment.apotheosis.mounted_strike       | WEAPON        | RARE      | 58 |
| apotheosis:natures_blessing              | enchantment.apotheosis.natures_blessing     | <null>        | RARE      | 74 |
| apotheosis:rebounding                    | enchantment.apotheosis.rebounding           | ARMOR         | RARE      | 75 |
| apotheosis:reflective                    | enchantment.apotheosis.reflective           | <null>        | RARE      | 68 |
| apotheosis:scavenger                     | enchantment.apotheosis.scavenger            | WEAPON        | VERY_RARE | 63 |
| apotheosis:shield_bash                   | enchantment.apotheosis.shield_bash          | <null>        | RARE      | 67 |
| apotheosis:splitting                     | enchantment.apotheosis.splitting            | <null>        | RARE      | 73 |
| apotheosis:stable_footing                | enchantment.apotheosis.stable_footing       | ARMOR_FEET    | RARE      | 60 |
| apotheosis:tempting                      | enchantment.apotheosis.tempting             | <null>        | UNCOMMON  | 66 |
| apotheosis:true_infinity                 | enchantment.apotheosis.true_infinity        | BOW           | VERY_RARE | 78 |
| astralsorcery:enchantment.as.nightvision | enchantment.as.nightvision                  | ARMOR         | VERY_RARE | 79 |
| astralsorcery:enchantment.as.smelting    | enchantment.as.smelting                     | DIGGER        | VERY_RARE | 80 |
| cofhcore:holding                         | enchantment.cofhcore.holding                | ALL           | UNCOMMON  | 38 |
| cofhcore:insight                         | enchantment.cofhcore.insight                | DIGGER        | UNCOMMON  | 39 |
| cofhcore:leech                           | enchantment.cofhcore.leech                  | WEAPON        | UNCOMMON  | 40 |
| cofhcore:multishot                       | enchantment.cofhcore.multishot              | BOW           | UNCOMMON  | 41 |
| cofhcore:smashing                        | enchantment.cofhcore.smashing               | DIGGER        | RARE      | 42 |
| cofhcore:smelting                        | enchantment.cofhcore.smelting               | DIGGER        | RARE      | 43 |
| cofhcore:soulbound                       | enchantment.cofhcore.soulbound              | ALL           | UNCOMMON  | 44 |
| cofhcore:vorpal                          | enchantment.cofhcore.vorpal                 | WEAPON        | RARE      | 45 |
| cyclicmagic:enchantment.beheading        | enchantment.beheading                       | WEAPON        | VERY_RARE | 46 |
| cyclicmagic:enchantment.expboost         | enchantment.expboost                        | DIGGER        | VERY_RARE | 56 |
| cyclicmagic:enchantment.launch           | enchantment.launch                          | ARMOR         | COMMON    | 47 |
| cyclicmagic:enchantment.quickdraw        | enchantment.quickdraw                       | BOW           | VERY_RARE | 52 |
| cyclicmagic:enchantment.reach            | enchantment.reach                           | ARMOR_CHEST   | VERY_RARE | 53 |
| cyclicmagic:enchantment.venom            | enchantment.venom                           | WEAPON        | COMMON    | 54 |
| cyclicmagic:enchantment.waterwalking     | enchantment.waterwalking                    | ARMOR_FEET    | VERY_RARE | 55 |
| draconicevolution:enchant_reaper         | enchantment.draconicevolution.reaperEnchant | WEAPON        | RARE      | 11 |
| enderio:repellent                        | enchantment.enderio.repellent               | ARMOR         | VERY_RARE | 36 |
| enderio:shimmer                          | enchantment.enderio.shimmer                 | ALL           | VERY_RARE | 30 |
| enderio:soulbound                        | enchantment.enderio.soulbound               | EC_REALLY_ALL | VERY_RARE | 29 |
| enderio:witherarrow                      | enchantment.enderio.witherarrow             | BOW           | UNCOMMON  | 31 |
| enderio:witherweapon                     | enchantment.enderio.witherweapon            | WEAPON        | UNCOMMON  | 28 |
| extrautils2:xu.bladerang                 | enchantment.xu.bladerang                    | BOOMERANG     | COMMON    | 15 |
| extrautils2:xu.boomereaperang            | enchantment.xu.boomereaperang               | BOOMERANG     | COMMON    | 23 |
| extrautils2:xu.burnerang                 | enchantment.xu.burnerang                    | BOOMERANG     | COMMON    | 14 |
| extrautils2:xu.kaboomerang               | enchantment.xu.kaboomerang                  | BOOMERANG     | COMMON    | 12 |
| extrautils2:xu.zoomerang                 | enchantment.xu.zoomerang                    | BOOMERANG     | COMMON    | 13 |
| gregtech:disjunction                     | enchantment.disjunction                     | WEAPON        | UNCOMMON  | 37 |
| minecraft:aqua_affinity                  | enchantment.waterWorker                     | ARMOR_HEAD    | RARE      |  6 |
| minecraft:bane_of_arthropods             | enchantment.damage.arthropods               | WEAPON        | UNCOMMON  | 18 |
| minecraft:binding_curse                  | enchantment.binding_curse                   | WEARABLE      | VERY_RARE | 10 |
| minecraft:blast_protection               | enchantment.protect.explosion               | ARMOR         | RARE      |  3 |
| minecraft:depth_strider                  | enchantment.waterWalker                     | ARMOR_FEET    | RARE      |  8 |
| minecraft:efficiency                     | enchantment.digging                         | DIGGER        | COMMON    | 32 |
| minecraft:feather_falling                | enchantment.protect.fall                    | ARMOR_FEET    | UNCOMMON  |  2 |
| minecraft:fire_aspect                    | enchantment.fire                            | WEAPON        | RARE      | 20 |
| minecraft:fire_protection                | enchantment.protect.fire                    | ARMOR         | UNCOMMON  |  1 |
| minecraft:flame                          | enchantment.arrowFire                       | BOW           | RARE      | 50 |
| minecraft:fortune                        | enchantment.lootBonusDigger                 | DIGGER        | RARE      | 35 |
| minecraft:frost_walker                   | enchantment.frostWalker                     | ARMOR_FEET    | RARE      |  9 |
| minecraft:infinity                       | enchantment.arrowInfinite                   | BOW           | VERY_RARE | 51 |
| minecraft:knockback                      | enchantment.knockback                       | WEAPON        | UNCOMMON  | 19 |
| minecraft:looting                        | enchantment.lootBonus                       | WEAPON        | RARE      | 21 |
| minecraft:luck_of_the_sea                | enchantment.lootBonusFishing                | FISHING_ROD   | RARE      | 61 |
| minecraft:lure                           | enchantment.fishingSpeed                    | FISHING_ROD   | RARE      | 62 |
| minecraft:mending                        | enchantment.mending                         | BREAKABLE     | RARE      | 70 |
| minecraft:power                          | enchantment.arrowDamage                     | BOW           | COMMON    | 48 |
| minecraft:projectile_protection          | enchantment.protect.projectile              | ARMOR         | UNCOMMON  |  4 |
| minecraft:protection                     | enchantment.protect.all                     | ARMOR         | COMMON    |  0 |
| minecraft:punch                          | enchantment.arrowKnockback                  | BOW           | RARE      | 49 |
| minecraft:respiration                    | enchantment.oxygen                          | ARMOR_HEAD    | RARE      |  5 |
| minecraft:sharpness                      | enchantment.damage.all                      | WEAPON        | COMMON    | 16 |
| minecraft:silk_touch                     | enchantment.untouching                      | DIGGER        | VERY_RARE | 33 |
| minecraft:smite                          | enchantment.damage.undead                   | WEAPON        | UNCOMMON  | 17 |
| minecraft:sweeping                       | enchantment.sweeping                        | WEAPON        | RARE      | 22 |
| minecraft:thorns                         | enchantment.thorns                          | ARMOR_CHEST   | VERY_RARE |  7 |
| minecraft:unbreaking                     | enchantment.durability                      | BREAKABLE     | UNCOMMON  | 34 |
| minecraft:vanishing_curse                | enchantment.vanishing_curse                 | ALL           | VERY_RARE | 71 |
| openblocks:explosive                     | enchantment.openblocks.explosive            | ARMOR         | RARE      | 25 |
| openblocks:flim_flam                     | enchantment.openblocks.flimflam             | ALL           | RARE      | 26 |
| randomthings:magnetic                    | enchantment.randomthings.magnetic           | DIGGER        | VERY_RARE | 24 |
+------------------------------------------+---------------------------------------------+---------------+-----------+----+
| Registry name                            | Name                                        | Type          | Rarity    | ID |
+------------------------------------------+---------------------------------------------+---------------+-----------+----+
```

Maybe it would be possible to use CraftTweaker to figure out the id?

https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Enchantments/IEnchantmentDefinition/

**Comment by Vyraal1** [comment] 2019-04-18 15:39
Hmm so with a fresh install, this is the NBT tag of the Satchel. 
![2019-04-18_11 37 17](https://user-images.githubusercontent.com/26587049/56373217-7d9b5580-61ce-11e9-98be-2ed119ec8db3.png)

I'm just tryign to figure out if your pack was modified in any way as it seems to be fixed on other server owners / players that I'm talking to. As far as I've seen, enchantment ID 39 is the norm.

**Comment by Vyraal1** [comment] 2019-04-18 15:39
`/ct hand` with the satchel also confirms as much 
![image](https://user-images.githubusercontent.com/26587049/56373308-aa4f6d00-61ce-11e9-912d-02d9cc58cb61.png)

**Comment by Vyraal1** [comment] 2019-04-18 15:42
https://gist.github.com/Vyraal1/e32766945e62267801b26f4f1c277bbf
This is the TellMe dump of our enchantments in the fresh install and dev instance.

**Comment by Vyraal1** [comment] 2019-04-18 15:45
Were there any modifications to the modlist (updates, additions, removals)? Is this on a Sponge server? Forge 2836?

**Comment by ZeekDaGeek** [comment] 2019-04-18 15:54
Changes interms of mods:
Added Crafting Tweaks -> Client Side + Server Side - Adds the ability to rotate the crafting table and press K to compress items into their 2x2 or 3x3 crafted counter parts in crafting tables.
Added Chat Tweaks + Twitch Integration -> Client Side - Adds the ability to have Twitch Chat in Minecraft.
Added Whitelister -> Server Side - Auto syncs my bots list of Minecraft users to the server's whitelist.
Added TrashSlot -> Client Optional + Server Sided - Just adds a trash slot.
Removed MineTogether -> Client Side - It's just an advertisment and it breaks anything that tries to edit Minecraft chat now.

Nothing adds any enchantments.

![waSrl](https://user-images.githubusercontent.com/1709288/56374231-e62f0600-61bf-11e9-89c6-b02d5cf24d86.png)

**Comment by Vyraal1** [comment] 2019-04-18 16:07
Ok I managed to reproduce this on 3rd (wtf?) installation of the pack. Looking into alternatives, the issue is that using NBT is completely out of the question as that still relies on the enchantment ID's. This might mean going forward there might not be a satchel combination for holding.

**Comment by ZeekDaGeek** [comment] 2019-04-18 17:01
This should be a more versatile way to reference the enchantments:

```
recipes.addShapeless(<thermalexpansion:satchel>.withTag(<enchantment:cofhcore:holding>.makeEnchantment(4).makeTag()), [
	<thermalexpansion:satchel>,
	<thermalexpansion:satchel>,
	<thermalexpansion:satchel>,
	<thermalexpansion:satchel>,
	<thermalexpansion:satchel>]);
```

**Comment by Vyraal1** [comment] 2019-04-18 21:00
Hmm bad news: existing worlds might get screwed up: 
![image](https://user-images.githubusercontent.com/26587049/56390996-69218200-61fb-11e9-9ce5-1d658368b98b.png)

**Comment by Vyraal1** [comment] 2019-04-18 21:06
https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-MC1120-Main/src/main/java/crafttweaker/mc1120/enchantments/MCEnchantment.java#L40

So according to here it still seems like that it relies on the registry ID's, CrT just ends up making it more readable, the problem still exists.

**Comment by TomyLobo** [comment] 2019-04-27 09:14
idea: change the quest to require 5 satchels of any type instead of 1 holding 4 satchel

**Comment by metaknight1992** [comment] 2019-05-01 21:56
running modpack version 1.4.2
modlist changes:
added Dank\Null 1.4.46
added TellMe 0.7.0

I dumped the enchantment table using TellMe, and compared my results to the table linked by Vyraal1 in post #6. Both tables have the same enchantments on them, in the same order.

However, the table posted by Vyraal1 has a blank id, as 38 is not assigned there.

I think new installs have just had all enchantments after that moved down by one, thus Holding, which was 39 before, now occupies the 38 slot. Insight, which was 40, is now 39.

**Comment by Vyraal1** [comment] 2019-05-08 17:09
Ended up just removing the enchantment requirement from the handy bag.

**Closed by Vyraal1** 2019-05-08 17:09 UTC
Labels: fixed in next update, help wanted, question
