### ISSUE TITLE
Mineralis still not properly generating the list of specified ores

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#304] opened 2019-04-13 20:16 UTC
Missing saltpeter, all thaum shards, biotite, rock salt, lepidolite. marble/diorite/granite/andesite variants non typical (chiseled variants/marble is astral runed marble)

Submitter: `IRSmoh_#5048`
Body: `OwO issue "Mineralis still not properly generating the list of specified ores" "Missing saltpeter, all thaum shards, biotite, rock salt, lepidolite. marble/diorite/granite/andesite variants non typical (chiseled variants/marble is astral runed marble)"`
Attachments:

**Comment by Saereth** [comment] 2019-04-14 23:07
I can't reproduce this, working fine for me in my dev version

**Comment by IRSmoh** [comment] 2019-04-15 06:16
I mean you could just test on bb, its broken there.

**Comment by Saereth** [comment] 2019-04-15 13:15
this appears to be a bug on astral's side, I'll get with hellfire about it

**Comment by rptbuddy** [comment] 2019-07-15 14:49
Still not working properly in modpack update 1.9.1...Having the same problems as op

**Comment by iComputerfreak** [comment] 2019-11-21 23:49
Since this problem was bugging me too, I found a workaround.
First, like suggested by HellFirePvP [here](https://github.com/HellFirePvP/AstralSorcery/issues/787), I added custom OreDict entries for each block that should spawn in the ritual. Then I added the correct form of Marble, Sandstone etc. as the only entry to that OreDict group.
After that the GregTech blocks (Infused Ores, Salt Ore, ...) still wouldn't spawn, so I added Custom Placeholder blocks using ContentTweaker. The blocks look the same and drop the GregTech variant when mined (even with silktouch).
So the ritual now basically spawns Placeholder blocks from ContentTweaker that look and behave like their GregTech counterpart (except for a few things, like hardness etc. maybe).

Anyone interested in the workaround, you can just download my zip and copy the contents to your instance folder.

The zip contains:
- The astralsorcery/mineralis_ritual.cfg using the new oreDictionary entries
- The textures for the new placeholder blocks
- Two scripts, one adding the placeholder blocks and one adding the new oreDictionary entries.
**Download**: [mineralis-fix.zip](https://github.com/FTBTeam/FTB-Interactions/files/3877256/mineralis-fix.zip)

**Comment by Saereth** [comment] 2020-05-19 13:14
Merged your fix in to the core repo, thanks @iComputerfreak 
https://github.com/FTBTeam/FTB-Interactions/commit/144d2877ff5915cdd014fa6e2c3320016f50e4cc

**Closed by Saereth** 2020-05-19 13:14 UTC
Labels: bug, mod issue
