### ISSUE TITLE
Recurring crash when starting world

### ISSUE THREAD

**Issue by littlebeast** [FTBTeam/FTB-Interactions#847] opened 2020-02-28 03:06 UTC
## Modpack Version: 
1.9.1

## Bug Report:
When first loading the world - after selecting the world to load, but before any gameplay; doesn't seem to occur on loading other dimensions - the game frequently crashes.  When it does, the window disappears, but the process still exists; however it doesn't do anything and just needs to be closed in task manager.  When it is, the launcher reopens with the crash report "Ticking entity".

## Expected Behavior/Suggestions:
...not crashing

## Is It Repeatable? Steps to Reproduce: 
Unknown.  However it does occur with alarming regularity.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/aa72d02e

## Mod/s Affected: 
unknown

## Known Fix: 
unknown

**Comment by Saereth** [comment] 2020-05-19 13:21
hrm crash seems related to microblock fences but this is definitely not something I'm seeing happen so there's some extenuating circumstance here I cant reproduce atm

**Comment by Saereth** [comment] 2020-05-24 17:04
lot of mods in question in that crashlog have been udated in the new version so im gonna close this for now, reopen if it happens in v2.0

**Closed by Saereth** 2020-05-24 17:04 UTC
Labels: Cannot Reproduce
