### ISSUE TITLE
No open computers cable or conduit

### ISSUE THREAD

**Issue by JasonQ1232** [FTBTeam/FTB-Interactions#1166] opened 2020-08-18 04:26 UTC
## Modpack Version: 
**FTB Interactions**

## Bug Report:

**No way to connect OC machines without having them touch, cables are needed**

## Expected Behavior/Suggestions:

**To have cables**

## Is It Repeatable? Steps to Reproduce: 

1.
2.

## Mod/s Affected: 

**Open Computers MAYBE EnderIO if you want that OC conduit (i do)**

## Known Fix: 

**Add conduit or cable or something.**
Technically you can make some complex wireless system using many computers and modems, but thats just stupid

**Comment by Possseidon** [comment] 2020-08-18 08:23
Duplicate of #1021

And yes, the ender-io conduit versions of OC cables would also be nice to have, but I would be happy with just the normal OC ones. ^^

**Closed** 2020-08-19 13:37 UTC
Labels: duplicate
