### ISSUE TITLE
add gas giants

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#705] opened 2019-06-17 15:57 UTC
and missions for gasses

Submitter: `Saereth#7836`
Body: `OwO issue "add gas giants" "and missions for gasses"`
Attachments:

**Comment by Saereth** [comment] 2020-05-26 13:15
basically a duplicate of https://github.com/FTBTeam/FTB-Interactions/issues/512 which is a much better issue so closing this one

**Closed by Saereth** 2020-05-26 13:15 UTC
Labels: auto, enhancement
