### ISSUE TITLE
2.0.5 - Cannot add more modifiers to shuriken 

### ISSUE THREAD

**Issue by jeremiahwinsley** [FTBTeam/FTB-Interactions#1083] opened 2020-08-05 03:41 UTC
## Modpack Version: 

2.0.5

## Bug Report:

When attempting to add more than 6 modifiers (or add creative modifiers after the limit has been reached)  to a Tinker's Construct shuriken made with 3 different materials, with free modifier slots, a message says I have reached the maximum modifiers and will not let me continue. If I replace blades until there are only two different materials, I can continue to add modifiers. I have not tested this with other Tinker's tool to see if the limit is also present there.

## Expected Behavior/Suggestions:

I should be able to continue adding modifiers as long as I have free slots, regardless of how many types of material I have.

## Is It Repeatable? Steps to Reproduce: 

1. Use any 4 knife blades of at least 3 different materials to make a shuriken.
2. Add creative modifiers as needed to bring the free slots past 7.
3. Add enough modifiers to use up 6 slots.
4. Upon attempting to add another modifier, you should see the message.
5. Replace knife blades until you have only two types of material.
6. Upon attempting to add another modifier, it should succeed.

**Comment by Saereth** [comment] 2020-08-05 13:31
There seems to be some weirdness in the way that modifiers calculate but dont actually use modifier slots, I believe this to be working as intended but it is intuitive. For example:
![image](https://user-images.githubusercontent.com/9200909/89418112-a023eb80-d6fd-11ea-872a-60339d068466.png)

 I have 7 modifiers on my shuriken allegedy
![image](https://user-images.githubusercontent.com/9200909/89418254-d06b8a00-d6fd-11ea-80a6-dbf3a098e4dd.png)

But because of the modifiers I'm getting from the tool parts, I'm actually already using 10 modifiers as you can see in the NBT tag data
![image](https://user-images.githubusercontent.com/9200909/89418310-e4af8700-d6fd-11ea-960e-f2840028b1ec.png)

This obviously becomes more pronounced when using modded metals with multiple modifiers per part such as this case I'm using enderium, evil infused, prismarine, ardite 
![image](https://user-images.githubusercontent.com/9200909/89418622-4ec82c00-d6fe-11ea-925a-7a6a8ed205ac.png)

Either way this would be for something for Tinker's construct to change or not, nothing we're doing from a pack perspective to make it behave this way so im gonna close this out

**Closed by Saereth** 2020-08-05 13:31 UTC
Labels: invalid, mod issue

**Comment by NoxyNixie** [comment] 2020-09-06 19:10
> Either way this would be for something for Tinker's construct to change or not, nothing we're doing from a pack perspective to make it behave this way so im gonna close this out

This is actually not a limitation in Tinkers Construct but rather a configurable limitation added by `Tinkers Extras`.

In: `config/TinkersExtras.cfg` there is:
```
    # Will set a limit on the amount of Modifiers allowed on a tool at once!
    I:"Modifier limit amount (per tool)"=10
```

So in essence this packs configuration is limiting the amount of modifiers per tool. My question would be is this a intended limitation or a minor oversight in the pack configuration?
